version: '3'

services:
  app:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./app:/app  # Mapea la carpeta completa 'app' del host a '/app' en el contenedor
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
    command: python /app/main.py  # Usa la ruta absoluta dentro del contenedor
